load balance

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,17 +1,75 @@
 #!/usr/bin/env bash
-# Ignore SC2154 for shellcheck
-# SC2154: `hostname` is referenced but not assigned.
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-sudo apt-get update -y
+echo -e "Updating and doing some minor checks...\n"
 
-sudo apt-get install -y nginx
+function install() {
+	command -v "$1" &> /dev/null
 
-HOSTNAME=$(hostname)
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
+install nginx
 
-sudo sed -i "/server_name _;/a \ \ \ \ add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
+echo -e "\nSetting up some minor stuff.\n"
 
-sudo service nginx restart
 
-curl -sI 127.0.0.1 | grep X-Served-By
+sudo ufw allow 'Nginx HTTP'
+
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+echo "Hello World!" > /var/www/html/index.html
+
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
